const fs = require('fs');

// Read existing cityServiceAreas
const existingPath = 'src/data/cityServiceAreas.ts';
let existingContent = fs.readFileSync(existingPath, 'utf8');

const missingCityData = [
  {
    slug: 'addison',
    cityName: 'Addison',
    county: 'Dallas County',
    code: 'ADD',
    zipCodes: ['75001'],
    headline: 'Dumpster Rental in Addison, TX',
    localIntro: 'Driveway-safe and commercial roll-off dumpster rentals in Addison, TX. Flat-rate pricing with no hidden drop-off fees for residential renovations and commercial build-outs near Addison Circle.',
    keyProjects: ['Addison Circle retail & office space renovations', 'Residential apartment & townhouse cleanouts', 'Restaurant remodeling and commercial debris hauling'],
    neighborhoods: ['Addison Circle', 'Les Lacs', 'Vitruvian Park', 'Midway Meadows'],
  },
  {
    slug: 'blue-mound',
    cityName: 'Blue Mound',
    county: 'Tarrant County',
    code: 'BM',
    zipCodes: ['76131'],
    headline: 'Dumpster Rental in Blue Mound, TX',
    localIntro: 'Affordable, flat-rate roll-off dumpster rentals delivered directly to residential properties and contractor job sites throughout Blue Mound, TX.',
    keyProjects: ['Home cleanouts and garage decluttering', 'Flooring tear-outs and drywall renovation debris', 'Yard waste and storm debris cleanup'],
    neighborhoods: ['Blue Mound North', 'Saginaw Crossing Border', 'Watauga Rd Corridor'],
  },
  {
    slug: 'cockrell-hill',
    cityName: 'Cockrell Hill',
    county: 'Dallas County',
    code: 'CH',
    zipCodes: ['75211'],
    headline: 'Dumpster Rental in Cockrell Hill, TX',
    localIntro: 'Compact, driveway-friendly roll-off dumpsters for Cockrell Hill homeowners, landlords, and remodeling contractors. Guaranteed on-time delivery with surface protection included.',
    keyProjects: ['Residential roofing and siding tear-offs', 'Kitchen & bathroom remodel cleanup', 'Rental property turnaround and tenant cleanouts'],
    neighborhoods: ['Cockrell Hill Central', 'West Dallas Border', 'Jefferson Blvd Corridor'],
  },
  {
    slug: 'double-oak',
    cityName: 'Double Oak',
    county: 'Denton County',
    code: 'DO',
    zipCodes: ['75077'],
    headline: 'Dumpster Rental in Double Oak, TX',
    localIntro: 'Driveway-safe 15, 20, and 25-yard roll-off container rentals in Double Oak, TX. Perfect for estate cleanouts, acreage clearing, and luxury home remodeling projects.',
    keyProjects: ['Large acreage landscape & storm debris cleanups', 'Custom home remodel and kitchen expansion debris', 'Estate cleanouts and pole barn decluttering'],
    neighborhoods: ['The Oaks', 'Taylor Oaks', 'Simmons Rd Estates', 'Kings Rd Corridor'],
  },
  {
    slug: 'edgecliff-village',
    cityName: 'Edgecliff Village',
    county: 'Tarrant County',
    code: 'EV',
    zipCodes: ['76134'],
    headline: 'Dumpster Rental in Edgecliff Village, TX',
    localIntro: 'Reliable, flat-rate roll-off dumpster delivery for homeowners and contractors in Edgecliff Village, TX. Clean equipment and wood driveway boards included on every drop.',
    keyProjects: ['Residential garage, attic, and shed cleanouts', 'Bathroom and kitchen remodeling waste disposal', 'Roofing replacement and siding project cleanup'],
    neighborhoods: ['Edgecliff South', 'Crowley Rd Corridor', 'Stonegate Border'],
  },
  {
    slug: 'everman',
    cityName: 'Everman',
    county: 'Tarrant County',
    code: 'EVM',
    zipCodes: ['76140'],
    headline: 'Dumpster Rental in Everman, TX',
    localIntro: 'Affordable roll-off dumpster rentals in Everman, TX with upfront flat rates and prompt same-day or next-day delivery for residential cleanups and trade contractor jobs.',
    keyProjects: ['Residential estate cleanouts and junk hauling', 'Drywall, flooring, and demolition debris', 'Yard debris and fence replacement cleanup'],
    neighborhoods: ['Everman Central', 'Enon Ave Area', 'Race St Neighborhood'],
  },
  {
    slug: 'forest-hill',
    cityName: 'Forest Hill',
    county: 'Tarrant County',
    code: 'FH',
    zipCodes: ['76119', '76140'],
    headline: 'Dumpster Rental in Forest Hill, TX',
    localIntro: 'Heavy-duty 15, 20, and 25-yard roll-off dumpster containers delivered across Forest Hill, TX. Perfect for home remodels, commercial cleanouts, and roofing tear-offs.',
    keyProjects: ['Commercial retail & warehouse junk removal', 'Residential roofing and remodeling waste', 'Full property cleanups and yard clearing'],
    neighborhoods: ['Forest Hill Gardens', 'Mansfield Hwy Corridor', 'Wichita St Area'],
  },
  {
    slug: 'haslet',
    cityName: 'Haslet',
    county: 'Tarrant County',
    code: 'HAS',
    zipCodes: ['76052'],
    headline: 'Dumpster Rental in Haslet, TX',
    localIntro: 'Driveway-safe dumpster rentals for growing residential subdivisions, custom acreage builds, and commercial logistics sites in Haslet, TX.',
    keyProjects: ['New construction & custom home debris management', 'Shop and outbuilding clearouts', 'Residential home improvement and landscaping disposal'],
    neighborhoods: ['Haslet Ridge', 'Caribou Ridge', 'Sendera Ranch Border', 'Blue Mound West'],
  },
  {
    slug: 'highland-park',
    cityName: 'Highland Park',
    county: 'Dallas County',
    code: 'HP',
    zipCodes: ['75205'],
    headline: 'Dumpster Rental in Highland Park, TX',
    localIntro: 'Discreet, driveway-safe luxury roll-off dumpster rentals in Highland Park, TX. Premium wood board driveway protection and clean equipment for premier residential estates.',
    keyProjects: ['High-end custom estate renovations and additions', 'Full interior remodel debris disposal', 'Architectural landscaping and hardscaping removal'],
    neighborhoods: ['Armstrong Pkwy Estates', 'Lakeside Dr', 'Dallas Country Club Area', 'Mockingbird Corridor'],
  },
  {
    slug: 'kennedale',
    cityName: 'Kennedale',
    county: 'Tarrant County',
    code: 'KEN',
    zipCodes: ['76060'],
    headline: 'Dumpster Rental in Kennedale, TX',
    localIntro: 'Prompt, flat-rate roll-off dumpster delivery throughout Kennedale, TX. Ideal for residential cleanouts, roofing contractors, and local business renovations.',
    keyProjects: ['Contractor job site waste management', 'Residential decluttering and move-out cleanouts', 'Deck and patio demolition debris removal'],
    neighborhoods: ['Kennedale South', 'Bowman Springs', 'Sublett Rd Area', 'Town Center'],
  },
  {
    slug: 'lake-worth',
    cityName: 'Lake Worth',
    county: 'Tarrant County',
    code: 'LW',
    zipCodes: ['76135'],
    headline: 'Dumpster Rental in Lake Worth, TX',
    localIntro: 'Driveway-friendly roll-off dumpsters in Lake Worth, TX. Flat-rate pricing with generous weight limits for lakefront property updates and commercial cleanouts.',
    keyProjects: ['Lakefront home dock & deck demolition debris', 'Residential kitchen, bath, and flooring renovations', 'Commercial shopping center cleanups along Lake Worth Blvd'],
    neighborhoods: ['Lakeshore Area', 'Lake Worth Blvd Corridor', 'Charbonneau', 'Hodgkins Rd Area'],
  },
  {
    slug: 'lakeside',
    cityName: 'Lakeside',
    county: 'Tarrant County',
    code: 'LKS',
    zipCodes: ['76108', '76135'],
    headline: 'Dumpster Rental in Lakeside, TX',
    localIntro: 'Fast, local roll-off dumpster rental services for Lakeside, TX homeowners and builders with wooden surface protection and flexible rental periods.',
    keyProjects: ['Residential roof replacement & siding disposal', 'Property brush and storm debris cleanouts', 'Home remodel & interior drywall disposal'],
    neighborhoods: ['Lakeside Estates', 'Jacksboro Hwy Corridor', 'Aquilla Dr Area'],
  },
  {
    slug: 'northlake',
    cityName: 'Northlake',
    county: 'Denton County',
    code: 'NLK',
    zipCodes: ['76226', '76247', '76262'],
    headline: 'Dumpster Rental in Northlake, TX',
    localIntro: 'Heavy-duty roll-off dumpsters for master-planned communities and commercial logistics developments across Northlake, TX near Texas Motor Speedway.',
    keyProjects: ['Master-planned residential new construction debris', 'Acreage barn and workshop cleanouts', 'Commercial retail and distribution facility build-outs'],
    neighborhoods: ['Harvest', 'Canyon Falls', 'The Ridge', 'Pecan Square Border'],
  },
  {
    slug: 'richland-hills',
    cityName: 'Richland Hills',
    county: 'Tarrant County',
    code: 'RH',
    zipCodes: ['76118'],
    headline: 'Dumpster Rental in Richland Hills, TX',
    localIntro: 'Driveway-safe roll-off container rentals in Richland Hills, TX. Transparent flat-rate pricing with wood driveway protection included for residential cleanouts.',
    keyProjects: ['Residential garage and attic decluttering', 'Single-room and full-home remodel cleanups', 'Contractor roofing and siding tear-offs'],
    neighborhoods: ['Richland Hills Central', 'Baker Blvd Corridor', 'Rosebud Park Area', 'Glenview Border'],
  },
  {
    slug: 'river-oaks',
    cityName: 'River Oaks',
    county: 'Tarrant County',
    code: 'RO',
    zipCodes: ['76114'],
    headline: 'Dumpster Rental in River Oaks, TX',
    localIntro: 'Compact, driveway-friendly roll-off dumpsters for homeowners and remodelers in River Oaks, TX. Fast drop-offs and seamless pickups.',
    keyProjects: ['Residential remodel and kitchen tear-outs', 'Yard debris, fence replacement, and tree clearing', 'Estate cleanouts and moving waste disposal'],
    neighborhoods: ['River Oaks Blvd Area', 'Long Ave Neighborhood', 'Blackstone Dr Area'],
  },
  {
    slug: 'roanoke',
    cityName: 'Roanoke',
    county: 'Denton County',
    code: 'RNK',
    zipCodes: ['76262'],
    headline: 'Dumpster Rental in Roanoke, TX',
    localIntro: 'The Unique Dining Capital of Texas trusts Lone Wolf Dumpsters for residential renovations, restaurant cleanouts, and commercial job site roll-offs.',
    keyProjects: ['Historic Oak Street restaurant remodel debris', 'Residential home improvement and cleanout waste', 'Commercial retail & light industrial waste management'],
    neighborhoods: ['Historic Downtown Roanoke', 'Briarwyck', 'Fairway Ranch', 'Chadwick Farms'],
  },
  {
    slug: 'saginaw',
    cityName: 'Saginaw',
    county: 'Tarrant County',
    code: 'SAG',
    zipCodes: ['76131', '76179'],
    headline: 'Dumpster Rental in Saginaw, TX',
    localIntro: 'Fast, dependable roll-off dumpster rentals in Saginaw, TX. Driveway protection boards included on every residential delivery for home renovations and junk disposal.',
    keyProjects: ['Residential kitchen & bathroom remodel debris', 'Roofing shingle tear-offs and contractor jobs', 'Garage decluttering and yard waste disposal'],
    neighborhoods: ['Willow Creek', 'Saginaw Springs', 'Highland Station', 'Basswood Border'],
  },
  {
    slug: 'sansom-park',
    cityName: 'Sansom Park',
    county: 'Tarrant County',
    code: 'SP',
    zipCodes: ['76114'],
    headline: 'Dumpster Rental in Sansom Park, TX',
    localIntro: 'Reliable and affordable dumpster rentals in Sansom Park, TX. Easy drive-in rear gate loading for residential cleanups and trade contractor debris.',
    keyProjects: ['Residential roof replacement cleanup', 'Home renovation and flooring tear-outs', 'Backyard clearing and fence removal debris'],
    neighborhoods: ['Sansom Park North', 'Jacksboro Hwy Area', 'Cowden St Corridor'],
  },
  {
    slug: 'trophy-club',
    cityName: 'Trophy Club',
    county: 'Denton County',
    code: 'TC',
    zipCodes: ['76262'],
    headline: 'Dumpster Rental in Trophy Club, TX',
    localIntro: 'Premier driveway-safe roll-off container rentals in Trophy Club, TX. Clean, well-maintained equipment and wooden surface boards for golf community properties.',
    keyProjects: ['Country club home luxury remodel debris', 'Kitchen expansion and master bath tear-outs', 'Landscape redesign and pool deck renovation waste'],
    neighborhoods: ['Trophy Club Country Club Estates', 'The Highlands', 'Hogan\'s Glen', 'Canterbury'],
  },
  {
    slug: 'university-park',
    cityName: 'University Park',
    county: 'Dallas County',
    code: 'UP',
    zipCodes: ['75205', '75225'],
    headline: 'Dumpster Rental in University Park, TX',
    localIntro: 'Discreet, driveway-safe dumpster rentals in University Park near SMU. Flat-rate pricing, clean equipment, and driveway protection for residential remodels.',
    keyProjects: ['Custom residential architecture and remodel debris', 'Student property move-out and estate cleanouts', 'Landscape redesign and masonry tear-out debris'],
    neighborhoods: ['SMU Campus District', 'Snider Plaza Area', 'Volk Estates Border', 'Preston Hollow Border'],
  },
  {
    slug: 'watauga',
    cityName: 'Watauga',
    county: 'Tarrant County',
    code: 'WAT',
    zipCodes: ['76148'],
    headline: 'Dumpster Rental in Watauga, TX',
    localIntro: 'Driveway-safe roll-off dumpster rentals in Watauga, TX. Fast, friendly delivery for garage cleanouts, roof replacements, and home improvement projects.',
    keyProjects: ['Residential garage decluttering & estate clearouts', 'Roofing shingle tear-offs and contractor jobs', 'Kitchen and bathroom renovation debris removal'],
    neighborhoods: ['Watauga Central', 'Park Vista Area', 'Whitley Rd Corridor', 'Capp Smith Park Area'],
  },
  {
    slug: 'westlake',
    cityName: 'Westlake',
    county: 'Denton County',
    code: 'WL',
    zipCodes: ['76262'],
    headline: 'Dumpster Rental in Westlake, TX',
    localIntro: 'Premier luxury dumpster rental service for Westlake, TX estates and corporate campuses. Pristine equipment, strict driveway protection, and tailored scheduling.',
    keyProjects: ['Luxury custom estate construction and remodels', 'Corporate campus build-out and tenant cleanouts', 'Extensive estate grounds clearing and landscaping removal'],
    neighborhoods: ['Vaquero', 'Granada', 'Entrada at Westlake', 'Terra Bella'],
  },
  {
    slug: 'white-settlement',
    cityName: 'White Settlement',
    county: 'Tarrant County',
    code: 'WS',
    zipCodes: ['76108'],
    headline: 'Dumpster Rental in White Settlement, TX',
    localIntro: 'Heavy-duty, driveway-friendly roll-off dumpster rentals in White Settlement, TX. Upfront pricing, included tonnage, and fast delivery for homeowners and contractors.',
    keyProjects: ['Residential cleanouts and garage organization', 'Roof replacement and drywall renovation waste', 'Commercial workshop and job site debris removal'],
    neighborhoods: ['White Settlement Central', 'Silver Creek Area', 'Clifford St Corridor', 'Cherry Ln Area'],
  },
];

console.log('Adding ' + missingCityData.length + ' missing cities to cityServiceAreas.ts...');

// Read cityServiceAreas.ts and append missing cities
let currentCode = fs.readFileSync('src/data/cityServiceAreas.ts', 'utf8');

// Find insertion point before ending bracket
const lastBracketIdx = currentCode.lastIndexOf('];');
if (lastBracketIdx !== -1) {
  let toAppend = '\n  // ==================== ADDITIONAL DFW CITIES ====================\n';
  missingCityData.forEach(city => {
    toAppend += '  ' + JSON.stringify(city, null, 4).replace(/\n/g, '\n  ') + ',\n';
  });
  
  const newContent = currentCode.slice(0, lastBracketIdx) + toAppend + currentCode.slice(lastBracketIdx);
  fs.writeFileSync('src/data/cityServiceAreas.ts', newContent, 'utf8');
  console.log('Successfully updated src/data/cityServiceAreas.ts!');
} else {
  console.error('Could not find ending bracket in src/data/cityServiceAreas.ts');
}
